apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.service.name }}
spec:
  serviceName: {{ .Values.db.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appLabel }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Values.db.secret.name }}
            - configMapRef:
                name: {{ .Values.db.service.name }}-config
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.db.storage }}
