apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
  DATABASE_URI: postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@db.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.database }}
