apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.secret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.POSTGRES_PASSWORD }}
  DATABASE_URI: postgresql://{{ .Values.db.secret.POSTGRES_USER }}:{{ .Values.db.secret.POSTGRES_PASSWORD }}@{{ .Values.db.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.db.config.POSTGRES_DB }}
