apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-db
spec:
  selector:
    app: {{ .Release.Name }}-cast-db
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
