apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
  selector:
    app: {{ .Values.db.appLabel }}
  clusterIP: None
