image:
  repository: hryla007/movieservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: movie-service
  port: 80
  targetPort: 8000
  nodePort: 30082

ingress:
  enabled: false  # Désactivé pour ce test, car on utilise NodePort

db:
  appLabel: movie-db
  service:
    name: movie-db
    port: 5432
    targetPort: 5432
  storage: 10Gi
  config:
    POSTGRES_DB: movie_db
    POSTGRES_HOST: movie-db
    POSTGRES_PORT: "5432"
  secret:
    name: movie-db-secret
    POSTGRES_USER: movie_admin
    POSTGRES_PASSWORD: movie_pwd
    DATABASE_URI: postgresql://movie_admin:movie_pwd@movie-db.{{ .Release.Namespace }}.svc.cluster.local:5432/movie_db
