replicaCount: 3

image:
  repository: hryla007/movieservice
  tag: helm
  pullPolicy: IfNotPresent

env:
  castServiceHostUrl: http://cast-service.staging.svc.cluster.local:8081/api/v1/casts/

service:
  name: movie-service
  port: 8082
  targetPort: 8082
  nodePort: 30082
  type: NodePort
  
castService:
  url: "http://cast-service.dev.svc.cluster.local:8081/api/v1/casts/"

ingress:
  enabled: false
  host: datascientestcours.cloudns.ch
  path: /api/v1/movies
  pathType: Prefix

db:
  appLabel: movie-db
  service:
    name: movie-db
    port: 5432
    targetPort: 5432
  storage: 10Gi
  config:
    POSTGRES_DB: movie_db
    POSTGRES_HOST: movie-db
    POSTGRES_PORT: "5432"
  secret:
    name: movie-db-secret
    POSTGRES_USER: movie_admin
    POSTGRES_PASSWORD: movie_pwd
    DATABASE_URI: postgresql://movie_admin:movie_pwd@movie-db.{{ .Release.Namespace }}.svc.cluster.local:5432/movie_db


