replicaCount: 3

image:
  repository: hryla007/movieservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: movie-service
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: datascientestcours.cloudns.ch
  path: /api/v1/movies

configMapName: movie-config
secretName: movie-db-secret
