apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: movie_admin
  POSTGRES_PASSWORD: movie_pwd
  DATABASE_URI: postgresql://movie_admin:movie_pwd@movie-db:5432/movie_db

