replicaCount: 3

image:
  repository: hryla007/castservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: cast-service
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: datascientestcours.cloudns.ch
  path: /api/v1/casts
  pathType: Prefix

db:
  appLabel: cast-db
  service:
    name: cast-db
    port: 5432
    targetPort: 5432
  storage: 10Gi
  config:
    POSTGRES_DB: cast_db
    POSTGRES_HOST: cast-db
    POSTGRES_PORT: "5432"
  secret:
    name: cast-db-secret
    POSTGRES_USER: cast_admin
    POSTGRES_PASSWORD: cast_pwd
    DATABASE_URI: postgresql://cast_admin:cast_pwd@cast-db.{{ .Release.Namespace }}.svc.cluster.local:5432/cast_db
