name: cast-service
namespace: dev
replicaCount: 3

image:
  repository: hryla007/castservice
  tag: latest

containerPort: 8000

configMapRef: cast-config
secretRef: cast-db-secret

ingress:
  enabled: true
  host: datascientestcours.cloudns.ch
  path: /api/v1/casts
