apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: cast_admin
  POSTGRES_PASSWORD: cast_pwd
  DATABASE_URI: postgresql://cast_admin:cast_pwd@cast-db.dev.svc.cluster.local:5432/cast_db
